# action 的名称
name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 生成静态文件
      - name: Docs
        run: npm run docs:build

      # 部署到 GitHub Pages
      - name: Deploy
        # 使用别人写好的一个 action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
          token: ${{ secrets.ACCESS_TOKEN }}
          # 打包后的文件部署到哪个分支上,例如gh-pages或docs。默认为gh-pages.
          branch: gh-pages
          # 打包后的文件在哪里
          folder: docs/.vitepress/dist